#ifndef CONFIG_HPP
#define CONFIG_HPP

#define VISUAL_DEBUGGING 1
//#define EUCLIDEAN_DISTANCE_FORMULA 1
//#define DRAW_INPUT_ITEM_BORDERS 1
//#define DRAW_OUTPUT_ITEM_BORDERS 1
//#define DRAW_ELEMENT_ITEM_BORDERS 1

#endif // CONFIG_HPP
